spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3307/parkingservice?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  show-sql: true

server:
  error:
    include-message: always

migrate-at-start: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
